# Generated by Django 4.0.6 on 2022-07-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='BlogIt', max_length=255),
        ),
    ]
